version: '2'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "8889:80" # web
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
        container_name: kryptos-app
    database:
        image: mysql:5.7.13
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=kryptosdb"
        ports:
            - "3316:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        container_name: kryptos-db