<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Kryptos</title>
    <meta name="description" content="Logowanie do aplikacji ABI.">
    <link href='http://fonts.googleapis.com/css?family=Tinos:400,700,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/assets/plugins/nifty-modal/css/component.css" rel="stylesheet"/>
    <link href="/_gfx/style.css" rel="stylesheet" type="text/css" />
    <link href="/_gfx/libs/ios7-switch/ios7-switch.css" rel="stylesheet" /> 
    <link href="/_gfx/libs/bootstrap-select2/select2.css" rel="stylesheet" type="text/css" />
    <link href="/_gfx/style_form.css" rel="stylesheet" type="text/css" />
    <link href="/_gfx/style-responsive.css" rel="stylesheet" />
</head>
<body class="fixed-left">
    {$layout->content nofilter}
  
    <script>

        var resizefunc = [];

    </script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src="assets/libs/jquery/jquery-1.11.1.min.js"></script>
    <script src="assets/libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/libs/jquery-ui-touch/jquery.ui.touch-punch.min.js"></script>
    <script src="assets/libs/bootstrap-select2/select2.min.js"></script>
    <script src="assets/libs/bootstrap-xeditable/js/bootstrap-editable.min.js"></script>
     <script src="assets/js/pages/advanced-forms.js"></script>
</body>
</html>